package mynyresolutionslist.nexmii.com.mynyresolutionslist.models.appdata;

/**
 * Created by David on 9/19/2019 for Nexmii.
 */
public class LocalMaterial {

    private final String[] goodWork = {

            "Keep it up!",
            "Don\'t stop here, keep working to achieve another goal",
            "Keep up the good work",
            "Good job",
            "Great. Stay focused",
            "Keep on working",
            "Keep Going"

    };

    private final String[] waysToKillAResolution = {

            "Your Resolution has been killed with a shotgun",
            "Your Resolution committed suicide",
            "Your Resolution was eaten by a hammer shark",
            "Your Resolution was obliterated by a hydrogen bomb",
            "Your Resolution removed his astronaut helmet in outer space",
            "Your Resolution was beaten up by bullies and died",
            "Your Resolution died in a sword fight",
            "Your Resolution was shot by its mother-in-law",
            "Your Resolution fell from the 67th floor of the Empire State building",
            "Your Resolution was ran over by a bus",
            "Your Resolution fell off a cliff",
            "Your Resolution ate a cyanide pill",
            "Your Resolution imploded",
            "Your Resolution was shot by a sniper",
            "Your Resolution was eaten by a shark",
            "Your Resolution was bit by a cobra",
            "Your Resolution jumped off a plane and the parachute did not open",
            "Your Resolution was beheaded!",
            "Your Resolution was cut in half by a chainsaw",
            "Your Resolution drowned",
            "Your Resolution was caught on fire",
            "Your Resolution exploded",
            "Your Resolution choked on maple syrup",
            "Your Resolution died in a gun fight"

    };

    private final String[] freeMotivationQuotes = {

            "If you want to achieve greatness stop asking for permission.",
            "Things work out best for those who make the best of how things work out.",
            "To live a creative life, we must lose our fear of being wrong.",
            "If you are not willing to risk the usual you will have to settle for the ordinary.",
            "Trust because you are willing to accept the risk, not because it’s safe or certain.",
            "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea.",
            "Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.",
            "All our dreams can come true if we have the courage to pursue them.",
            "Good things come to people who wait, but better things come to those who go out and get them.",
            "If you do what you always did, you will get what you always got.",
            "Success is walking from failure to failure with no loss of enthusiasm.",
            "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
            "Successful entrepreneurs are givers and not takers of positive energy.",
            "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.",
            "Opportunities don’t happen, you create them.",
            "Try not to become a person of success, but rather try to become a person of value.",
            "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
            "I have not failed. I’ve just found 10,000 ways that won’t work.",
            "If you don’t value your time, neither will others. Stop giving away your time and talents- start charging for it.",
            "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
            "No one can make you feel inferior without your consent.",
            "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
            "If you’re going through hell keep going.",
            "The ones who are crazy enough to think they can change the world, are the ones that do.",
            "Don’t raise your voice, improve your argument.",
            "What seems to us as bitter trials are often blessings in disguise.",
            "The meaning of life is to find your gift. The purpose of life is to give it away.",
            "The distance between insanity and genius is measured only by success.",
            "When you stop chasing the wrong things you give the right things a chance to catch you.",
            "Don’t be afraid to give up the good to go for the great.",
            "No masterpiece was ever created by a lazy artist."

    };

    private String[] lifeMotivationalQuotes = {

            "Life is about making an impact, not making an income. - Kevin Kruse",
            "Whatever the mind of man can conceive and believe, it can achieve. - Napoleon Hill",
            "Strive not to be a success, but rather to be of value. - Albert Einstein",
            "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference. - Robert Frost",
            "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
            "You miss 100% of the shots you don’t take. - Wayne Gretzky",
            "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed. - Michael Jordan",
            "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
            "Every strike brings me closer to the next home run. - Babe Ruth",
            "Definiteness of purpose is the starting point of all achievement. - W. Clement Stone",
            "Life isn't about getting and having, it's about giving and being. - Kevin Kruse",
            "Life is what happens to you while you’re busy making other plans. - John Lennon",
            "We become what we think about. - Earl Nightingale",
            "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover. - Mark Twain",
            "Life is 10% what happens to me and 90% of how I react to it. - Charles Swindoll",
            "The most common way people give up their power is by thinking they don’t have any. - Alice Walker",
            "The mind is everything. What you think you become. - Buddha",
            "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
            "An unexamined life is not worth living. - Socrates",
            "Eighty percent of success is showing up. - Woody Allen",
            "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
            "Winning isn’t everything, but wanting to win is. - Vince Lombardi",
            "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
            "Every child is an artist.  The problem is how to remain an artist once he grows up. - Pablo Picasso",
            "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
            "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
            "Either you run the day, or the day runs you. - Jim Rohn",
            "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
            "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
            "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it. - Johann Wolfgang von Goethe",
            "The best revenge is massive success. - Frank Sinatra",
            "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily. - Zig Ziglar",
            "Life shrinks or expands in proportion to one's courage. - Anais Nin",
            "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced. - Vincent Van Gogh",
            "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. - Aristotle",
            "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you. - Jesus",
            "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
            "Go confidently in the direction of your dreams.  Live the life you have imagined. - Henry David Thoreau",
            "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me. - Erma Bombeck",
            "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him. - Booker T. Washington",
            "Certain things catch your eye, but pursue only those that capture the heart. - Ancient Indian Proverb",
            "Believe you can and you’re halfway there. - Theodore Roosevelt",
            "Everything you’ve ever wanted is on the other side of fear. - George Addair",
            "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. - Plato",
            "Teach thy tongue to say,'I do not know,' and thous shalt progress. - Maimonides",
            "Start where you are. Use what you have.  Do what you can. - Arthur Ashe",
            "When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life. - John Lennon",
            "Fall seven times and stand up eight. - Japanese Proverb",
            "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. - Helen Keller",
            "Everything has beauty, but not everyone can see. - Confucius",
            "How wonderful it is that nobody need wait a single moment before starting to improve the world. - Anne Frank",
            "When I let go of what I am, I become what I might be. - Lao Tzu",
            "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Maya Angelou",
            "Happiness is not something readymade.  It comes from your own actions. - Dalai Lama",
            "If you're offered a seat on a rocket ship, don't ask what seat! Just get on. - Sheryl Sandberg",
            "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end. - Aristotle",
            "If the wind will not serve, take to the oars. - Latin Proverb",
            "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground. - Unknown",
            "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained. - Marie Curie",
            "Too many of us are not living our dreams because we are living our fears. - Les Brown",
            "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
            "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
            "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. - Leonardo da Vinci",
            "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless. - Jamie Paolinetti",
            "You take your life in your own hands, and what happens? A terrible thing, no one to blame. - Erica Jong",
            "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. - Bob Dylan",
            "I didn’t fail the test. I just found 100 ways to do it wrong. - Benjamin Franklin",
            "In order to succeed, your desire for success should be greater than your fear of failure. - Bill Cosby",
            "A person who never made a mistake never tried anything new. - Albert Einstein",
            "The person who says it cannot be done should not interrupt the person who is doing it. - Chinese Proverb",
            "There are no traffic jams along the extra mile. - Roger Staubach",
            "It is never too late to be what you might have been. - George Eliot",
            "You become what you believe. - Oprah Winfrey",
            "I would rather die of passion than of boredom. - Vincent van Gogh",
            "A truly rich man is one whose children run into his arms when his hands are empty. - Unknown",
            "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings. - Ann Landers",
            "If you want your children to turn out well, spend twice as much time with them, and half as much money. - Abigail Van Buren",
            "Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray",
            "The battles that count aren't the ones for gold medals. The struggles within yourself, the invisible battles inside all of us, that's where it's at. - Jesse Owens",
            "Education costs money.  But then so does ignorance. - Sir Claus Moser",
            "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
            "It does not matter how slowly you go as long as you do not stop. - Confucius",
            "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey",
            "Remember that not getting what you want is sometimes a wonderful stroke of luck. - Dalai Lama",
            "You can’t use up creativity.  The more you use, the more you have. - Maya Angelou",
            "Dream big and dare to fail. - Norman Vaughan",
            "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
            "Do what you can, where you are, with what you have. - Teddy Roosevelt",
            "If you do what you’ve always done, you’ll get what you’ve always gotten. - Tony Robbins",
            "Dreaming, after all, is a form of planning. - Gloria Steinem",
            "It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live. - Mae Jemison",
            "You may be disappointed if you fail, but you are doomed if you don't try. - Beverly Sills",
            "Remember no one can make you feel inferior without your consent. - Eleanor Roosevelt",
            "Life is what we make it, always has been, always will be. - Grandma Moses",
            "The question isn’t who is going to let me; it’s who is going to stop me. - Ayn Rand",
            "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford",
            "It’s not the years in your life that count. It’s the life in your years. - Abraham Lincoln",
            "Change your thoughts and you change your world. - Norman Vincent Peale",
            "Either write something worth reading or do something worth writing. - Benjamin Franklin",
            "Nothing is impossible, the word itself says, “I’m possible!”. - Audrey Hepburn",
            "The only way to do great work is to love what you do. - Steve Jobs",
            "If you can dream it, you can achieve it. - Zig Ziglar"
    };

    private String[] successMotivationalQuotes = {
            "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
            "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
            "Things work out best for those who make the best of how things work out. - John Wooden",
            "Entrepreneurs average 3.8 failures before final success. What sets the successful ones apart is their amazing persistence. - Lisa M. Amos",
            "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
            "Take up one idea. Make that one idea your life, think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. - Swami Vivekananda",
            "Stop chasing the money and start chasing the passion. - Tony Hsieh",
            "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
            "If you are willing to do more than you are paid to do, eventually you will be paid to do more than you do. - Anonymous",
            "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
            "Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them. - Vaibhav Shah",
            "Success? I don't know what that word means. I'm happy. But success, that goes back to what in somebody's eyes success means. For me, success is inner peace. That's a good day for me. - Denzel Washington",
            "Opportunities don't happen. You create them. - Chris Grosser",
            "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
            "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
            "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
            "The best revenge is massive success. - Frank Sinatra",
            "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
            "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
            "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
            "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
            "If you're going through hell, keep going. - Winston Churchill",
            "What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde",
            "The distance between insanity and genius is measured only by success. - Bruce Feirstein",
            "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
            "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. - Nathaniel Hawthorne",
            "If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
            "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. - Ray Goforth",
            "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
            "People ask, 'What's the best role you've ever played?' The next one. - Kevin Kline",
            "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
            "The starting point of all achievement is desire. - Napoleon Hill",
            "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
            "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. - Thomas J. Watson",
            "All progress takes place outside the comfort zone. - Michael John Bobak",
            "You may only succeed if you desire succeeding; you may only fail if you do not mind failing. - Philippos",
            "Courage is resistance to fear, mastery of fear--not absence of fear. - Mark Twain",
            "Only put off until tomorrow what you are willing to die having left undone. - Pablo Picasso",
            "We become what we think about most of the time, and that's the strangest secret. - Earl Nightingale",
            "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
            "I don't know the key to success, but the key to failure is trying to please everyone. - Bill Cosby",
            "Though no one can go back and make a brand-new start, anyone can start from now and make a brand-new ending. - Carl Bard",
            "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. - Martha Stewart",
            "Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover. - Mark Twain",
            "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. - Mark Caine",
            "Whenever you find yourself on the side of the majority, it is time to pause and reflect. - Mark Twain",
            "The successful warrior is the average man, with laserlike focus. - Bruce Lee",
            "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I have never heard of anyone ever stumbling on something sitting down. - Charles F. Kettering",
            "If you genuinely want something, don't wait for it--teach yourself to be impatient. - Gurbaksh Chahal",
            "You can't connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future. You have to trust in something--your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life. - Steve Jobs",
            "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! - T. Harv Eker",
            "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. - Jim Rohn",
            "The No. 1 reason people fail in life is because they listen to their friends, family, and neighbors. - Napoleon Hill",
            "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. - Jane Smiley",
            "Success does not consist in never making mistakes but in never making the same one a second time. - George Bernard Shaw",
            "I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. - Diane Ackerman",
            "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
            "Our greatest fear should not be of failure ... but of succeeding at things in life that don't really matter. - Francis Chan",
            "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much. - Jim Rohn",
            "Nobody ever wrote down a plan to be broke, fat, lazy, or stupid. Those things are what happen when you don't have a plan. - Larry Winget",
            "To be successful you must accept all challenges that come your way. You can't just accept the ones you like. - Mike Gafka",
            "Be content to act, and leave the talking to others. - Baltasar",
            "You may have to fight a battle more than once to win it. - Margaret Thatcher",
            "Be patient with yourself. Self-growth is tender; it's holy ground. There's no greater investment. - Stephen Covey",
            "I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite. - G. K. Chesterton",
            "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
            "The greater the artist, the greater the doubt. Perfect confidence is granted to the less talented as a consolation prize. - Robert Hughes",
            "What would you attempt to do if you knew you would not fail. - Robert Schuller",
            "Always bear in mind that your own resolution to success is more important than any other one thing. - Abraham Lincoln",
            "Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential. - John Maxwell",
            "Would you like me to give you a formula for success? It's quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn't at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember, that's where you will find success. - Thomas J. Watson",
            "Logic will get you from A to B. Imagination will take you everywhere. - Albert Einstein",
            "Success is just a war of attrition. Sure, there's an element of talent you should probably possess. But if you just stick around long enough, eventually something is going to happen. - Dax Shepard",
            "My tombstone? I'm thinking something along the lines of, 'Geez, he was just here a minute ago.' - George Carlin"
    };

    private String[] happinessMotivationalQuotes = {
            "Dream as if you'll live forever, live as if you'll die today. - James Dean",
            "Doing what you like is freedom. Liking what you do is happiness. - Frank Tyger",
            "Be happy with what you have. Be excited about what you want. - Alan Cohen",
            "Life is a journey, and if you fall in love with the journey, you will be in love forever. - Peter Hagerty",
            "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
            "Much of the stress that people feel doesn't come from having too much to do. It comes from not finishing what they've started. - David Allen",
            "We forge the chains we wear in life. - Charles Dickens",
            "If you look to others for fulfillment, you will never be fulfilled. If your happiness depends on money, you will never be happy with yourself. Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the world belongs to you. - Lao Tzu",
            "Everything is a gift of the universe--even joy, anger, jealousy, frustration, or separateness. Everything is perfect either for our growth or our enjoyment. - Ken Keyes Jr.",
            "There is no such thing as a problem without a gift for you in its hands. You seek problems because you need their gifts. - Richard Bach",
            "If you want to be happy, set a goal that commands your thoughts, liberates your energy, and inspires your hopes. - Andrew Carnegie",
            "Tension is who you think you should be, relaxation is who you are. - Chinese Proverb",
            "For me it is sufficient to have a corner by my hearth, a book, and a friend, and a nap undisturbed by creditors or grief. - Fernandez de Andrada",
            "You cannot judge what should bring others joy, and others cannot judge what should bring you joy. - Alan Cohen",
            "The art of living lies less in eliminating our troubles than growing with them. - Bernard M. Baruch",
            "Our capacity to draw happiness from aesthetic objects or material goods in fact seems critically dependent on our first satisfying a more important range of emotional or psychological needs, among them the need for understanding, for love, expression, and respect. - Alain de Botton",
            "If you start to think the problem is 'out there,' stop yourself. That thought is the problem. - Stephen Covey",
            "Happiness cannot be traveled to, owned, earned, worn, or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude. - Denis Waitley",
            "Happiness is not a station you arrive at, but a manner of traveling. - Margaret Lee Runbeck",
            "Security is when everything is settled, when nothing can happen to you; security is the denial of life. - Germaine Greer",
            "Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it. - Greg Anderson",
            "Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared. - Buddha",
            "The best remedy for those who are afraid, lonely, or unhappy is to go outside, somewhere where they can be quiet, alone with the heavens, nature, and God. As long as this exists, and it certainly always will, then there will be comfort for every sorrow, whatever the circumstances may be. - Anne Frank",
            "In our lives, change is unavoidable, loss is unavoidable. In the adaptability and ease with which we experience change, lies our happiness and freedom. - Buddha",
            "Live with intention. Walk to the edge. Listen hard. Practice wellness. Play with abandon. Laugh. Choose with no regret. Do what you love. Live as if this is all there is. - Mary Anne Roadacher-Hershey",
            "You never regret being kind. - Nicole Shepherd",
            "They who can give up essential liberty to obtain a little temporary safety, deserve neither liberty nor safety. - Ben Franklin",
            "Forgiveness does not change the past, but it does enlarge the future. - Paul Boese",
            "The secret of health for both mind and body is not to mourn for the past, worry about the future, or anticipate troubles, but to live in the present moment wisely and earnestly. - Buddha",
            "True happiness is not attained through self-gratification, but through fidelity to a worthy purpose. - Helen Keller",
            "Money is neither my god nor my devil. It is a form of energy that tends to make us more of who we already are, whether it's greedy or loving. - Dan Millman",
            "The need for forgiveness is an illusion. There is nothing to forgive. - Rachel England",
            "Blessed are those who can give without remembering and take without forgetting. - Bernard Meltzer",
            "Reflect upon your present blessings, of which every man has many--not on your past misfortunes, of which all men have some. - Charles Dickens",
            "Even a happy life cannot be without a measure of darkness, and the word happy would lose its meaning if it were not balanced by sadness. It is far better to take things as they come along with patience and equanimity.-  Carl Jung",
            "He who lives in harmony with himself lives in harmony with the universe. - Marcus Aurelius",
            "If you want others to be happy, practice compassion. If you want to be happy, practice compassion. - Dalai Lama",
            "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. - Helen Keller",
            "Happiness is not having what you want. It is appreciating what you have. - Unknown",
            "True happiness...arises, in the first place, from the enjoyment of one's self. - Joseph Addison",
            "Happiness is that state of consciousness which proceeds from the achievement of one's values. - Ayn Rand",
            "Most of us are just about as happy as we make up our minds to be. - William Adams",
            "Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie",
            "We can have peace if we let go of wanting to change the past and wanting to control the future. - Lester Levinson",
            "We make a living by what we get; we make a life by what we give. - Winston Churchill",
            "Money doesn't bring happiness and creativity. Your creativity and happiness brings money. - Sam Rosen",
            "Happiness is the experience of loving life. Being happy is being in love with that momentary experience. And love is looking at someone or even something and seeing the absolute best in him/her or it. Love is happiness with what you see. So love and happiness really are the same thing...just expressed differently. - Robert McPhillips",
            "Everything that irritates us about others can lead us to an understanding of ourselves. - Carl Jung",
            "God, grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference. - Reinhold Niebuhr",
            "I am not bound to win, I am bound to be true. I am not bound to succeed, but I am bound to live up to the light I have. - Abraham Lincoln",
            "Gratitude unlocks the fullness of life. It turns what we have into enough and more. It turns denial into acceptance, chaos to order, confusion to clarity. It can turn a meal into a feast, a house into a home, a stranger into a friend. Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow. - Melody Beattie",
            "There is no stress in the world, only people thinking stressful thoughts and then acting on them. - Wayne Dyer",
            "We all get report cards in many different ways, but the real excitement of what you're doing is in the doing of it. It's not what you're gonna get in the end--it's not the final curtain--it's really in the doing it, and loving what you're doing. - Ralph Lauren",
            "In the midst of movement and chaos, keep stillness inside of you. - Deepak Chopra",
            "Success at the highest level comes down to one question: Can you decide that your happiness can come from someone else's success? - Bill Walton",
            "There is only one thing more painful than learning from experience and that is not learning from experience. - Archibald McLeish",
            "Once you do something you love, you never have to work again. - Willie Hill",
            "Anything in life that we don't accept will simply make trouble for us until we make peace with it. - Shakti Gawain",
            "The right way is not always the popular and easy way. Standing for right when it is unpopular is a true test of moral character. - Margaret Chase Smith",
            "Persons of high self-esteem are not driven to make themselves superior to others; they do not seek to prove their value by measuring themselves against a comparative standard. Their joy is being who they are, not in being better than someone else. - Nathaniel Branden",
            "Anxiety is the dizziness of freedom. - Soren Kierkegaard",
            "Do what you have always done and you'll get what you have always got. - Sue Knight",
            "The happiness of life is made up of the little charities of a kiss or smile, a kind look, a heartfelt compliment. - Samuel Taylor Coleridge",
            "We avoid the things that we're afraid of because we think there will be dire consequences if we confront them. But the truly dire consequences in our lives come from avoiding things that we need to learn about or discover. - Shakti Gawain",
            "Think of what you have rather than of what you lack. Of the things you have, select the best and then reflect how eagerly you would have sought them if you did not have them. - Marcus Aurelius",
            "Happiness is where we find it, but very rarely where we seek it. - J. Petit Senn",
            "To be content means that you realize you contain what you seek. - Alan Cohen",
            "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven. - John Milton",
            "In our daily lives, we must see that it is not happiness that makes us grateful, but the gratefulness that makes us happy. - Albert Clarke",
            "Look at everything as though you were seeing it either for the first or last time. Then your time on earth will be filled with glory. - Betty Smith",
            "You are responsible for your life. You can't keep blaming somebody else for your dysfunction. Life is really about moving on. - Oprah Winfrey",
            "Expecting life to treat you well because you are a good person is like expecting an angry bull not to charge because you are a vegetarian. - Shari R. Barr",
            "View your life from your funeral: Looking back at your life experiences, what have you accomplished? What would you have wanted to accomplish but didn't? What were the happy moments? What were the sad? What would you do again, and what wouldn't you do? - Victor Frankl",
            "Far better is it to dare mighty things, to win glorious triumphs, even though checkered by failure, than to rank with those poor spirits who neither enjoy much nor suffer much, because they live in a gray twilight that knows not victory nor defeat. - Theodore Roosevelt",
            "Boredom is the feeling that everything is a waste of time...serenity, that nothing is. - Thomas Szasz"
    };

    public String[] getLifeMotivationalQuotes() {
        return lifeMotivationalQuotes;
    }

    public String[] getSuccessMotivationalQuotes() {
        return successMotivationalQuotes;
    }

    public String[] getHappinessMotivationalQuotes() {
        return happinessMotivationalQuotes;
    }

    public String[] getGoodWork() {
        return goodWork;
    }

    public String[] getWaysToKillAResolution() {
        return waysToKillAResolution;
    }

    public String[] getFreeMotivationQuotes() {
        return freeMotivationQuotes;
    }

}
